spring:
  application:
    name: "26-ApiGateway"
  cloud:
    gateway:
      routes:
        - id: "24-Welcome-API"
          uri: "lb://24-Welcome-API"
          predicates:
            - Path=/welcome
        - id: "25-Greet-API"
          uri: "lb://25-Greet-API"
          predicates:
            - Path=/greet

    
server:
  port: 3333
  
